# Generated by Django 4.2.5 on 2023-10-02 00:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0003_alter_assignment_students_and_more'),
        ('students', '0002_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Student',
        ),
    ]
