# Generated by Django 4.2.5 on 2023-10-02 19:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_remove_lesson_sequence_number_alter_lesson_content_and_more'),
        ('teachers', '0007_alter_lesson_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discussion',
            name='teacher',
        ),
        migrations.DeleteModel(
            name='File',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='course',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='students',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='teacher',
        ),
        migrations.AlterField(
            model_name='lessonenrollment',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.lesson'),
        ),
        migrations.DeleteModel(
            name='Discussion',
        ),
        migrations.DeleteModel(
            name='Lesson',
        ),
    ]
