# Generated by Django 4.2.5 on 2023-10-23 18:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_enrollment'),
        ('teachers', '0010_choice_question_response_choice_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quizzes', to='courses.course'),
        ),
    ]
