# Generated by Django 4.2.5 on 2023-10-28 18:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_enrollment'),
        ('teachers', '0012_alter_grade_assignment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grade',
            name='grade',
        ),
        migrations.AddField(
            model_name='assignment',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='courses.course'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='title',
            field=models.CharField(db_column='quiz_title', max_length=100),
        ),
    ]
