# Generated by Django 4.2.5 on 2023-10-28 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0013_remove_grade_grade_assignment_course_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='grade',
            name='grade',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
