# Generated by Django 4.2.5 on 2023-10-28 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0014_grade_grade'),
    ]

    operations = [
        migrations.AddField(
            model_name='grade',
            name='attempt_number',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
