# Generated by Django 4.2.7 on 2023-11-05 15:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0015_grade_attempt_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='grade',
            name='question',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='teachers.question'),
        ),
    ]
