# Generated by Django 4.2.7 on 2023-11-06 01:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('teachers', '0016_grade_question'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grade',
            name='attempt_number',
        ),
        migrations.RemoveField(
            model_name='grade',
            name='question',
        ),
        migrations.RemoveField(
            model_name='grade',
            name='quiz',
        ),
        migrations.RemoveField(
            model_name='grade',
            name='student',
        ),
        migrations.CreateModel(
            name='Attempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempt_number', models.PositiveIntegerField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teachers.quiz')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('student', 'quiz', 'attempt_number')},
            },
        ),
        migrations.AddField(
            model_name='grade',
            name='attempt',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='teachers.attempt'),
        ),
        migrations.AddField(
            model_name='response',
            name='attempt',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='teachers.attempt'),
        ),
    ]
