# Generated by Django 4.2.7 on 2023-11-06 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0017_remove_grade_attempt_number_remove_grade_question_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attempt',
            name='final_grade',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
