# Generated by Django 4.2.7 on 2023-11-07 00:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0018_attempt_final_grade'),
    ]

    operations = [
        migrations.AddField(
            model_name='grade',
            name='question',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='teachers.question'),
        ),
    ]
