# Generated by Django 4.2.7 on 2023-11-07 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0019_grade_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='attempt',
            name='completed_timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attempt',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
    ]
