# Generated by Django 4.2.5 on 2023-10-02 19:20

import courses.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0008_remove_discussion_teacher_delete_file_and_more'),
        ('courses', '0004_remove_lesson_sequence_number_alter_lesson_content_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='teacher',
            field=models.ForeignKey(default=courses.models.default_teacher, on_delete=django.db.models.deletion.CASCADE, to='teachers.teacher'),
        ),
    ]
